"""new usermodel

Revision ID: 25fb93b83728
Revises: 76f01b7febf3
Create Date: 2024-02-19 17:55:36.340169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fb93b83728'
down_revision: Union[str, None] = '76f01b7febf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
