"""New

Revision ID: 4a445efcf16a
Revises: 898622d59d53
Create Date: 2024-02-16 20:29:33.674432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a445efcf16a'
down_revision: Union[str, None] = '898622d59d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.drop_column('attachments', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'file_data')
    # ### end Alembic commands ###
