"""add field control_date

Revision ID: 5dbffc187f2d
Revises: 464549cdf3a0
Create Date: 2024-03-01 14:25:29.632362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbffc187f2d'
down_revision: Union[str, None] = '464549cdf3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('control_date', sa.Date(), nullable=True))
    op.drop_constraint('tickets_system_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'systems', ['system_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_system_id_fkey', 'tickets', 'systems', ['system_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tickets', 'control_date')
    # ### end Alembic commands ###
