"""new usermodel

Revision ID: 868f8aa6e5dd
Revises: 25fb93b83728
Create Date: 2024-02-19 18:01:57.677521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868f8aa6e5dd'
down_revision: Union[str, None] = '25fb93b83728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
