"""new

Revision ID: 898622d59d53
Revises: 999fc4ac9049
Create Date: 2024-02-16 16:08:26.735707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '898622d59d53'
down_revision: Union[str, None] = '999fc4ac9049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('attachments', 'file_data')
    op.drop_column('attachments', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attachments', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'file_path')
    op.drop_column('attachments', 'filename')
    # ### end Alembic commands ###
