"""new

Revision ID: 999fc4ac9049
Revises: f4d65be8e2c2
Create Date: 2024-02-16 13:22:10.676647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '999fc4ac9049'
down_revision: Union[str, None] = 'f4d65be8e2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    op.add_column('attachments', sa.Column('ticket_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'attachments', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('attachments', 'file_path')
    op.alter_column('tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'updated_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('tickets', 'created_at',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('attachments', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'ticket_id')
    op.drop_column('attachments', 'file_data')
    # ### end Alembic commands ###
