"""New

Revision ID: a767212d6bd6
Revises: 4a445efcf16a
Create Date: 2024-02-16 22:16:27.944819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a767212d6bd6'
down_revision: Union[str, None] = '4a445efcf16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_url', sa.String(), nullable=False))
    op.drop_column('attachments', 'file_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('file_data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('attachments', 'file_url')
    # ### end Alembic commands ###
