"""new add system 3

Revision ID: bce97fd8c387
Revises: abd8fac2df36
Create Date: 2024-02-21 10:41:29.843607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce97fd8c387'
down_revision: Union[str, None] = 'abd8fac2df36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('tickets', sa.Column('system_id', sa.Integer, nullable=False, server_default='0'))
    # Предполагается, что в таблице 'systems' есть id  0 для системы по умолчанию
    op.execute('UPDATE tickets SET system_id =   0 WHERE system_id IS NULL')
    op.alter_column('tickets', 'system_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'system_id')
    # ### end Alembic commands ###
