"""new

Revision ID: d0fc750832ac
Revises: f7d9cca359d6
Create Date: 2024-02-15 13:11:38.336172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0fc750832ac'
down_revision: Union[str, None] = 'f7d9cca359d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attachments_message_id_fkey', 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('attachments_message_id_fkey', 'attachments', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
