"""new usermodel

Revision ID: d2c1d6b260ea
Revises: e12f20bf08c6
Create Date: 2024-02-19 16:24:25.879932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c1d6b260ea'
down_revision: Union[str, None] = 'e12f20bf08c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Добавляем столбец _password с возможностью содержать NULL значения
    op.add_column('users', sa.Column('_password', sa.String(), nullable=True))

    # Обновляем все существующие записи, чтобы установить значение _password равным текущему значению password
    op.execute("UPDATE users SET _password = password")

    # Изменяем столбец _password, чтобы он стал NOT NULL
    op.alter_column('users', '_password', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
