"""new usermodel

Revision ID: d71eefdc2ef5
Revises: d2c1d6b260ea
Create Date: 2024-02-19 16:42:16.818487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71eefdc2ef5'
down_revision: Union[str, None] = 'd2c1d6b260ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
