"""new

Revision ID: f7d9cca359d6
Revises: 960a8538cd5e
Create Date: 2024-02-15 13:00:30.305537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7d9cca359d6'
down_revision: Union[str, None] = '960a8538cd5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ticket_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_assigned_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('messages', 'assigned_id')
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('assigned_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_assigned_id_fkey', 'messages', 'users', ['assigned_id'], ['id'])
    op.drop_column('messages', 'ticket_id')
    # ### end Alembic commands ###
