version: '3.8'
services:
 postgres:
    container_name: Support_db
    image: "postgres:latest"
    env_file:
      - .env-non-dev
    ports:
      - "5433:5432"
    volumes:
      - ./alembic:/app/alembic
 redis:
    image: "redis:alpine"
    container_name: Support_redis
    ports:
      - "6380:6379"
 backend:
    container_name: Support_back
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "7777:8000"
    env_file:
      - .env-non-dev  
    depends_on:
      - postgres
      - redis
    command: ./docker/app.sh
 frontend:
    container_name: Support_front
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - HOST=0.0.0.0
    depends_on:
      - backend
    
  