from datetime import date, datetime
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database import AKTPAKBase

class AKPC_LPU(AKTPAKBase):
    __tablename__ = 'AKPC_LPU'

    STATE: Mapped[int] = mapped_column(nullable=True)
    COUNTER: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    CODE: Mapped[int] = mapped_column(nullable=True)
    LPUCODE: Mapped[int] = mapped_column(nullable=False)
    TYPE_S: Mapped[int] = mapped_column(nullable=True)
    NAME: Mapped[str] = mapped_column(nullable=True)
    NAME_L: Mapped[str] = mapped_column(nullable=True)
    NAME_S: Mapped[str] = mapped_column(nullable=True)
    OMS: Mapped[int] = mapped_column(nullable=True)
    PMSP_YES: Mapped[int] = mapped_column(nullable=True)
    DENT_YES: Mapped[int] = mapped_column(nullable=True)
    AGE: Mapped[int] = mapped_column(nullable=True)
    INDEX: Mapped[str] = mapped_column(nullable=True)
    RGN1: Mapped[int] = mapped_column(nullable=True)
    RGN2: Mapped[int] = mapped_column(nullable=True)
    RGN3: Mapped[int] = mapped_column(nullable=True)
    STREET: Mapped[int] = mapped_column(nullable=True)
    HOUSE: Mapped[int] = mapped_column(nullable=True)
    HOUSELITER: Mapped[str] = mapped_column(nullable=True)
    CORPUS: Mapped[int] = mapped_column(nullable=True)
    FLAT: Mapped[int] = mapped_column(nullable=True)
    FLATLITER: Mapped[str] = mapped_column(nullable=True)
    E_MAIL: Mapped[str] = mapped_column(nullable=True)
    NPOST: Mapped[str] = mapped_column(nullable=True)
    FACE: Mapped[str] = mapped_column(nullable=True)
    PHONE: Mapped[int] = mapped_column(nullable=True)
    FAX: Mapped[int] = mapped_column(nullable=True)
    FACE1: Mapped[str] = mapped_column(nullable=True)
    PHONE1: Mapped[int] = mapped_column(nullable=True)
    NPOST3: Mapped[str] = mapped_column(nullable=True)
    FACE3: Mapped[str] = mapped_column(nullable=True)
    E_MAIL3: Mapped[str] = mapped_column(nullable=True)
    PHONE3: Mapped[int] = mapped_column(nullable=True)
    INN: Mapped[str] = mapped_column(nullable=True)
    OGRN: Mapped[str] = mapped_column(nullable=True)
    OWERCODE: Mapped[int] = mapped_column(nullable=True)
    NN_LPU: Mapped[str] = mapped_column(nullable=True)
    DOMAIN: Mapped[int] = mapped_column(nullable=True)
    CHIEF: Mapped[int] = mapped_column(nullable=True)
    EKATC: Mapped[str] = mapped_column(nullable=True)
    OKPO: Mapped[str] = mapped_column(nullable=True)
    SOATO: Mapped[int] = mapped_column(nullable=True)
    SOOGU: Mapped[int] = mapped_column(nullable=True)
    KPP: Mapped[str] = mapped_column(nullable=True)
    TER: Mapped[int] = mapped_column(nullable=True)
    RAZDEL: Mapped[int] = mapped_column(nullable=True)
    D_START: Mapped[datetime] = mapped_column(nullable=True)
    D_MODIF: Mapped[datetime] = mapped_column(nullable=True)
    D_FIN: Mapped[datetime] = mapped_column(nullable=True)
    KOPF: Mapped[int] = mapped_column(nullable=True)
    OID: Mapped[str] = mapped_column(nullable=True)
    FOMSCODE: Mapped[str] = mapped_column(nullable=True)
    WWW: Mapped[str] = mapped_column(nullable=True)
    NN_TER: Mapped[str] = mapped_column(nullable=True)
    AOID: Mapped[str] = mapped_column(nullable=True)
    HOUSEID: Mapped[str] = mapped_column(nullable=True)
    LATITUDE: Mapped[str] = mapped_column(nullable=True)
    LONGITUDE: Mapped[str] = mapped_column(nullable=True)
    PERSMOD: Mapped[str] = mapped_column(nullable=True)
    UNIQID: Mapped[int] = mapped_column(nullable=True)


    # Отношения с другими моделями, если они есть
    # tickets = relationship("Ticket", back_populates="period")
    # users = relationship("User", back_populates="period")